Repository Yelp/paasta, pull requests merged in 2020-01, with the labels that each got.

#2612 U/mathieu/rightsizer manual mem too
  paasta_tools/contrib/paasta_update_soa_memcpu.py
Labels: enhancement

#2617 remove paasta validate for tron directory
  paasta_tools/cli/cmds/validate.py
  tests/cli/test_cmds_validate.py
Labels: in review

#2616 fix paasta schema bug
  paasta_tools/cli/schemas/adhoc_schema.json
  paasta_tools/cli/schemas/kubernetes_schema.json
  paasta_tools/cli/schemas/marathon_schema.json
Labels: in review

#2641 Don't add smartstack annotation if service is not a smartstack service
  debian/changelog
  paasta_tools/__init__.py
  paasta_tools/kubernetes_tools.py
  tests/test_kubernetes_tools.py
  yelp_package/Makefile
Labels: bug

#2635 Fix JIRA import issue and add filter to Splunk criteria
  paasta_tools/contrib/paasta_update_soa_memcpu.py
Labels: bug

#2642 Adding separate annotation for ip requiring services on k8s
  paasta_tools/kubernetes_tools.py
  tests/test_kubernetes_tools.py
Labels: enhancement
